# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-25 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=6, upload_to='images/'),
            preserve_default=False,
        ),
    ]
